### PR TITLE
Fix for the uploadAccountResponse for correct error message/reason

### PR DESCRIPTION
**Pull request by amohabir**
Fix in the UploadAccountResponse object for mapping the error message.

### CODE REVIEW

**Comment by hiranya911** [comment]
@amohabir did you actually see the server responding with `errorMessage` instead of `message`? The existing implementation is consistent with how the responses are parsed in the Node.js SDK: https://github.com/firebase/firebase-admin-node/blob/master/test/unit/auth/user-import-builder.spec.ts#L570

@bojeil-google any thoughts?

**Comment by amohabir** [comment]
@hiranya911 Yep, I actually verified this by debugging up to the HTTP call in the Java code.

**Comment by hiranya911** [comment]
Thank you @amohabir. I can also repro the problem by slightly modifying one of the integration tests. I'll make that part of the test suite, so this gets verified in the future (you're also welcome to do so in this PR). Can you add an entry to the `CHANGELOG` file? Then I can merge this.

@bojeil-google we will need to fix this in Node.js too.

**Comment by amohabir** [comment]
I updated the CHANGELOG.

**Comment by hiranya911** [comment]
This has been fixed in the Auth backend. Reverting this change.

**Pull request merged**
